[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/galleries/*"
  to = "/photos/:splat"
  status = 301

[[redirects]]
  from = "/projects/2018-software/"
  to = "/projects"
  status = 301
