name: 🚀 Deploy website on push

on:
  push:
    branches: [ main, github_deploy ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ssh.strato.de
        port: 22
        protocol: ftps
        username: www.veeck.de
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/
        server-dir: veeck/
        log-level: verbose
